version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb+srv://olaranmmy_db_user:4j4Of5aSp2qTJH04@cluster0.mha5l7e.mongodb.net/ecommerce?retryWrites=true&w=majority
      - MONGO_URI=mongodb+srv://olaranmmy_db_user:4j4Of5aSp2qTJH04@cluster0.mha5l7e.mongodb.net/ecommerce?retryWrites=true&w=majority
      - JWT_SECRET=6d0368553c88105c12580fec0eaef55ce4b19a19755dc9dfe4d70efd9c52ccab
    restart: always

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend
    restart: always

  admin:
    build:
      context: ./Admin
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3001:80"
    env_file:
      - ./Admin/.env
    depends_on:
      - backend
    restart: always